# Generated by Django 4.0.5 on 2022-06-26 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['delivery_no']},
        ),
        migrations.AddField(
            model_name='delivery',
            name='in_transit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DeliveryAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('received', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveryassets', to='assets.asset')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.delivery')),
            ],
            options={
                'unique_together': {('delivery', 'asset')},
            },
        ),
    ]
